dist: focal
language: python
python: 
  - "3.6"
branches:
  only:
    - master
    - develop
sudo: false
install:
# fix travis issues
- sudo apt-key del 656408E390CFB1F5
- wget -qO - https://www.mongodb.org/static/pgp/server-4.4.asc | sudo apt-key add -

# install deps
- pip install pyyaml jsonschema pysha3 
- sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
- sudo apt-get update
- sudo apt-get install --only-upgrade libstdc++6

script:

# sanitation checks against testsets
- wget http://retesteth.ethdevops.io/retesteth
- chmod +x ./retesteth
- ./retesteth --version
- ./retesteth -t GeneralStateTests -- --checkhash --all --testpath $(pwd)
- ./retesteth -t BlockchainTests -- --checkhash --all --testpath $(pwd)
- ./retesteth -t BCGeneralStateTests -- --checkhash --all --testpath $(pwd)
- ./retesteth -t LegacyTests -- --checkhash --all --testpath $(pwd)
- ./retesteth -t TransactionTests -- --checkhash --all --testpath $(pwd)
- ./retesteth -t DifficultyTests -- --checkhash --all --testpath $(pwd)
- ./retesteth -t EIPTests -- --checkhash --all --testpath $(pwd)
- ./retesteth -t EOFTests -- --checkhash --all --testpath $(pwd)

# Retesteth does the format check upon test run and generation
#- make sani
